baseurl = "https://casecommons.github.io/aws-docs/"
languageCode = "en-us"
title = "AWS CloudFormation Tutorial"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
pygmentsuseclasses = true
publishDir = "docs"

[params]
  # General information
  author = "Justin Menga"
  description = "AWS CloudFormation Tutorial"
  copyright = "Released under the AGPL license"

  # Repository
  # provider = "GitHub"
  # repo_url = "https://github.com/casecommons/aws-cloudformation"

  version = "v0.1"
  logo = "images/logo.png"
  favicon = ""

  permalink = "#"

  # Custom assets
  custom_css = []
  custom_js  = []

  # Syntax highlighting theme
  highlight_css  = ""

  [params.palette]
      primary = "red"
      accent  = "teal"

    [params.font]
      text = "Ubuntu"
      code = "Ubuntu Mono"

[social]
  twitter = "jmenga"
  github  = "mixja"
  email   = "justin.menga@gmail.com"


[[menu.main]]
  name   = "Introduction"
  url    = "/"
  weight = 0

[[menu.main]]
  name   = "Local Setup"
  url    = "local-setup/"
  weight = 10

[[menu.main]]
  name   = "Security Resources"
  url    = "security-resources/"
  weight = 20

[[menu.main]]
  name   = "CloudFormation Resources"
  url    = "cloudformation-resources/"
  weight = 30

[[menu.main]]
  name   = "Network Resources"
  url    = "network-resources/"
  weight = 40

[[menu.main]]
  name   = "EC2 Container Registry Resources"
  url    = "ecr-resources/"
  weight = 50

[[menu.main]]
  name   = "Web Proxy Stack"
  url    = "web-proxy/"
  weight = 60

[[menu.main]]
  name   = "Intake API Stack"
  url    = "intake-api/"
  weight = 70

[[menu.main]]
  name   = "Intake Accelerator Stack"
  url    = "intake-accelerator/"
  weight = 80


[blackfriday]
  smartypants = true
  fractions = true
  smartDashes = true
  plainIDAnchors = true
