# STS role in the target AWS account to assume
sts_role_arn: "arn:aws:iam::094411466117:role/admin"

# IAM Groups
config_iam_groups:
  DemoResourcesAdmins:
    Policies:
      - PolicyName: "AssumeDemoResourcesAdminRole"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
              - "sts:AssumeRole"
              Resource: "arn:aws:iam::160775127577:role/admin"
              